"""
Subagent Progress Monitor - V3.1.0
10-minute interval progress reporting
Ported from v2.1.0 Node.js to Python
"""

import threading
import time
from datetime import datetime
from pathlib import Path
from typing import Optional, Callable


class SubagentProgressMonitor:
    """
    Monitors subagent progress and reports every 10 minutes.
    
    Usage:
        monitor = SubagentProgressMonitor("task_001", "My Task")
        monitor.start()
        
        # Do work...
        monitor.report("Phase 1 complete", 25.0)
        
        # More work...
        monitor.complete("Task finished")
    """
    
    DEFAULT_INTERVAL = 600  # 10 minutes in seconds
    
    def __init__(
        self,
        task_id: str,
        task_name: str,
        progress_file: Optional[str] = None,
        report_interval: int = DEFAULT_INTERVAL,
        report_callback: Optional[Callable] = None
    ):
        self.task_id = task_id
        self.task_name = task_name
        self.report_interval = report_interval
        self.report_callback = report_callback or self._default_report
        
        # Progress file path
        if progress_file:
            self.progress_file = Path(progress_file)
        else:
            date_str = datetime.now().strftime("%Y-%m-%d")
            self.progress_file = Path(
                f"/root/.openclaw/workspace/task_backlog/"
                f"task_{task_id}_progress_{date_str}.md"
            )
        
        self.start_time = time.time()
        self.last_report_time = 0
        self.phase = "init"
        self.completion = 0.0
        self._running = False
        self._timer: Optional[threading.Timer] = None
    
    def _default_report(self, message: str, status: str) -> None:
        """Default report handler - prints to console"""
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] [{self.task_id}] {status}: {message}")
    
    def start(self) -> None:
        """Start monitoring"""
        self._running = True
        self._create_progress_file()
        self.report("Monitoring started", "started")
        self._schedule_next_report()
    
    def stop(self) -> None:
        """Stop monitoring"""
        self._running = False
        if self._timer:
            self._timer.cancel()
    
    def _schedule_next_report(self) -> None:
        """Schedule next automatic report"""
        if not self._running:
            return
        
        self._timer = threading.Timer(self.report_interval, self._auto_report)
        self._timer.daemon = True
        self._timer.start()
    
    def _auto_report(self) -> None:
        """Automatic periodic report"""
        if not self._running:
            return
        
        elapsed = int(time.time() - self.start_time)
        message = f"Phase: {self.phase}, Completion: {self.completion:.1f}%, Elapsed: {elapsed}s"
        self.report(message, "progress")
        
        # Schedule next
        self._schedule_next_report()
    
    def report(self, message: str, status: str = "progress") -> None:
        """Report progress"""
        self.report_callback(message, status)
        self._update_progress_file(message, status)
        self.last_report_time = time.time()
    
    def update(self, phase: Optional[str] = None, completion: Optional[float] = None) -> None:
        """Update progress state"""
        if phase:
            self.phase = phase
        if completion is not None:
            self.completion = completion
    
    def complete(self, final_message: str = "Task completed") -> None:
        """Mark task as complete"""
        self.completion = 100.0
        self.phase = "completed"
        self.report(final_message, "completed")
        self.stop()
    
    def _create_progress_file(self) -> None:
        """Create initial progress file"""
        self.progress_file.parent.mkdir(parents=True, exist_ok=True)
        
        content = f"""# Task Progress: {self.task_name}

**Task ID:** {self.task_id}  
**Status:** running  
**Started:** {datetime.now().isoformat()}  
**Next Report:** {(datetime.now().timestamp() + self.report_interval)}  

## Progress Summary
- Phase: {self.phase}
- Completion: {self.completion:.1f}%
- ETA: Calculating...

## Activity Log
- [{datetime.now().strftime("%H:%M:%S")}] Monitoring started

---

*Auto-generated by SubagentProgressMonitor*
"""
        self.progress_file.write_text(content, encoding='utf-8')
    
    def _update_progress_file(self, message: str, status: str) -> None:
        """Update progress file"""
        if not self.progress_file.exists():
            return
        
        content = self.progress_file.read_text(encoding='utf-8')
        timestamp = datetime.now().strftime("%H:%M:%S")
        
        # Update summary
        content = content.replace(
            f"- Phase: {self.phase}",
            f"- Phase: {self.phase}"
        ).replace(
            f"- Completion: {self.completion:.1f}%",
            f"- Completion: {self.completion:.1f}%"
        )
        
        # Add log entry
        log_entry = f"- [{timestamp}] [{status.upper()}] {message}\n"
        content = content.replace("## Activity Log\n", f"## Activity Log\n{log_entry}")
        
        self.progress_file.write_text(content, encoding='utf-8')


class MonitorContext:
    """Context manager for easy monitor usage"""
    
    def __init__(self, task_id: str, task_name: str, **kwargs):
        self.monitor = SubagentProgressMonitor(task_id, task_name, **kwargs)
    
    def __enter__(self):
        self.monitor.start()
        return self.monitor
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is None:
            self.monitor.complete()
        else:
            self.monitor.report(f"Error: {exc_val}", "error")
            self.monitor.stop()
        return False
